/* AUTO-GENERATED by tools/build-photos.py — do not edit by hand.
   Run the script after dropping photos into photos-raw/dN/ to refresh this file. */
window.tripPhotos = {
  day1: [],
  day2: [],
  day3: [],
  day4: [],
  day5: [],
};
